parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Auto-tag all handlers implementing the interface
    _instanceof:
        App\Handler\Notification\NotificationHandlerInterface:
            tags: ['app.notification_handler']

    # Configure the registry to use tagged services
    App\Handler\Notification\NotificationHandlerRegistry:
        arguments:
            $handlers: !tagged_iterator app.notification_handler

    App\Client\Twillio:
        class: App\Client\Twillio
        arguments:
            $id: '%env(TWILLIO_ID)%'
            $token: '%env(TWILLIO_TOKEN)%'
            $fromNumber: '%env(TWILLIO_NUMBER)%'