name: Backend CD - Build Image

# Trigger workflow on main/master pushes, feature/setup-ci-backend, or manually
on:
  push:
    branches:
      - main
      - master
      - feature/setup-ci-backend
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

  build:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Only login to registry for main/master branches (where we'll push)
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract branch name for tagging
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch

      # Set whether to push based on branch
      - name: Set Push Flag
        id: push_flag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "SHOULD_PUSH=true" >> $GITHUB_ENV
          else
            echo "SHOULD_PUSH=false" >> $GITHUB_ENV
          fi

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          # Replace with your actual image name
          images: your-dockerhub-username/your-backend-image
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
            type=raw,value=${{ env.BRANCH_NAME }}
            type=sha,format=short
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          # Only push for main/master
          push: ${{ env.SHOULD_PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # For feature branches, output that the build succeeded but wasn't pushed
      - name: Output build status for feature branch
        if: github.ref == 'refs/heads/feature/setup-ci-backend'
        run: |
          echo "✅ Docker image build successful!"
          echo "Image was built with tags: ${{ steps.meta.outputs.tags }}"
          echo "Image was NOT pushed to registry (only done for main/master)"
          echo "This build confirms your Dockerfile is valid"

      # For main/master, output push confirmation
      - name: Output push confirmation
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "Image pushed with tags: ${{ steps.meta.outputs.tags }}"