name: Frontend CD - Build and Push Image

on:
  push:
    branches:
      - main
      - develop
      - acceptance

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to GitHub Container Registry using the built-in GITHUB_TOKEN
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          # Use GitHub Container Registry format
          images: ghcr.io/${{ github.repository_owner }}/quote-gen-frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
            type=raw,value=${{ env.DOCKER_SAFE_BRANCH }}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output push details
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "Image pushed with tags: ${{ steps.meta.outputs.tags }}"
          echo ""
          echo "To pull this image, run:"
          
          # Extract the first tag for demo purposes
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          echo "docker pull ${FIRST_TAG}"